-- BuildLogicPCS Database Schema

CREATE TABLE IF NOT EXISTS CPU (
    CPU_ID INTEGER PRIMARY KEY,
    Brand TEXT NOT NULL,
    Model TEXT NOT NULL,
    Socket_Type TEXT NOT NULL,
    Core_Count INTEGER NOT NULL,
    Thread_Count INTEGER NOT NULL,
    Base_Clock REAL NOT NULL,
    Boost_Clock REAL NOT NULL,
    Power_Draw INTEGER NOT NULL,
    Performance_Score INTEGER NOT NULL,
    Price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS GPU (
    GPU_ID INTEGER PRIMARY KEY,
    Brand TEXT NOT NULL,
    Model TEXT NOT NULL,
    PCIE_Version TEXT NOT NULL,
    Power_Draw INTEGER NOT NULL,
    VRAM INTEGER NOT NULL,
    Performance_Score INTEGER NOT NULL,
    Price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS MOTHERBOARD (
    MOBO_ID INTEGER PRIMARY KEY,
    Brand TEXT NOT NULL,
    Model TEXT NOT NULL,
    Socket_Type TEXT NOT NULL,
    Form_Factor TEXT NOT NULL,
    RAM_Type TEXT NOT NULL,
    Has_NVME INTEGER NOT NULL CHECK (Has_NVME IN (0, 1)),
    Max_RAM INTEGER NOT NULL,
    PCIE_Version REAL NOT NULL,
    Price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS RAM (
    RAM_ID INTEGER PRIMARY KEY,
    Brand TEXT NOT NULL,
    Model TEXT NOT NULL,
    RAM_Type TEXT NOT NULL,
    Capacity INTEGER NOT NULL,
    Is_Dual_Channel INTEGER NOT NULL CHECK (Is_Dual_Channel IN (0, 1)),
    Speed REAL NOT NULL,
    Performance_Score INTEGER NOT NULL,
    Price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS PSU (
    PSU_ID INTEGER PRIMARY KEY,
    Brand TEXT NOT NULL,
    Model TEXT NOT NULL,
    Wattage INTEGER NOT NULL,
    Efficiency_Rating TEXT NOT NULL,
    Price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS "CASE" (
    Case_ID INTEGER PRIMARY KEY,
    Brand TEXT NOT NULL,
    Model TEXT NOT NULL,
    Form_Factor TEXT NOT NULL,
    Max_GPU_Length INTEGER NOT NULL,
    Has_Fans INTEGER NOT NULL CHECK (Has_Fans IN (0, 1)),
    Price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS GAMES (
    Game_ID INTEGER PRIMARY KEY,
    Game_Title TEXT NOT NULL,
    Release_Year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS GAMES_PRESET_APPLIED (
    Game_Preset TEXT NOT NULL,
    Game_ID INTEGER NOT NULL,
    Game_Preset_Score INTEGER NOT NULL,
    Minimum_CPU_Score INTEGER NOT NULL,
    Minimum_GPU_Score INTEGER NOT NULL,
    PRIMARY KEY (Game_Preset, Game_ID),
    FOREIGN KEY (Game_ID) REFERENCES GAMES (Game_ID)
);

CREATE TABLE IF NOT EXISTS BUILD (
    Build_ID INTEGER PRIMARY KEY,
    CPU_ID INTEGER NOT NULL,
    GPU_ID INTEGER NOT NULL,
    MOBO_ID INTEGER NOT NULL,
    RAM_ID INTEGER NOT NULL,
    PSU_ID INTEGER NOT NULL,
    Case_ID INTEGER NOT NULL,
    Total_Power_Draw INTEGER NOT NULL,
    Total_Price REAL NOT NULL,
    Logic_Score INTEGER NOT NULL,
    FOREIGN KEY (CPU_ID) REFERENCES CPU (CPU_ID),
    FOREIGN KEY (GPU_ID) REFERENCES GPU (GPU_ID),
    FOREIGN KEY (MOBO_ID) REFERENCES MOTHERBOARD (MOBO_ID),
    FOREIGN KEY (RAM_ID) REFERENCES RAM (RAM_ID),
    FOREIGN KEY (PSU_ID) REFERENCES PSU (PSU_ID),
    FOREIGN KEY (Case_ID) REFERENCES "CASE" (Case_ID)
);

CREATE TABLE IF NOT EXISTS COMPATIBILITY_RULES (
    Rule_ID INTEGER PRIMARY KEY,
    Component_A INTEGER NOT NULL,
    Component_B INTEGER NOT NULL,
    Condition TEXT NOT NULL,
    Rule_Description TEXT NOT NULL
);
